name: "Prepare NodeJS"
description: "Set up NodeJS, (optionally) perform clean install of NPM dependencies"

inputs:
  node_version:
    description: "NodeJS version to use"
    default: "20"
  cache:
    description: "Cache type. Supported values: npm, yarn, pnpm"
    default: "npm"
  clean_install:
    description: "Perform a clean install of the dependencies"
    default: "false"
  registry_url:
    description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.cache }}
        registry-url: ${{ inputs.registry_url }}
    - name: Install dependencies
      if: ${{ fromJSON(inputs.clean_install) }} # workaround for composite jobs not being able to pass boolean inputs
      shell: bash
      run: |
        npm ci
