name: "Prepare NodeJS"
description: "Set up NodeJS, (optionally) perform clean install of NPM dependencies"

inputs:
  node-version:
    description: "NodeJS version to use"
    default: "22"
  cache:
    description: "Cache type. Supported values: npm, yarn, pnpm"
    default: "npm"
  clean-install:
    description: "Perform a clean install of the dependencies"
    default: "false"
  registry-url:
    description: "Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN"
    default: ""

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
        registry-url: ${{ inputs.registry-url }}
    - name: Install dependencies
      if: ${{ fromJSON(inputs.clean-install) }} # workaround for composite jobs not being able to pass boolean inputs
      shell: bash
      run: |
        npm ci
