version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/actions/**"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: scope
    ignore:
      - dependency-name: "epam/ai-dial-ci"
    open-pull-requests-limit: 100
    cooldown:
      default-days: 7
