version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/actions/**"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    commit-message:
      # Prefix all commit messages with "chore: "
      prefix: "chore"
    open-pull-requests-limit: 0
