name: "Prepare Python"
description: "Checkout project, set up python"

inputs:
  python_version:
    description: "Python version to use"
    default: "3.x"
  cache:
    description: "Cache type. Supported values: pip, pipenv, poetry"
    default: "poetry"
  install_poetry:
    description: "Install poetry"
    default: "true"
  poetry_version:
    description: "Poetry version to use"
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      if: ${{ fromJSON(inputs.install_poetry) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        version: ${{ inputs.poetry_version }}
    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ inputs.python_version }}
        cache: ${{ inputs.cache }}
