name: "Prepare Python"
description: "Checkout project, set up python"

inputs:
  python-version:
    description: "Python version to use"
    default: "3.x"
  cache:
    description: "Cache type. Supported values: pip, pipenv, poetry"
    default: "poetry"
  poetry-install:
    description: "Install poetry"
    default: "true"
  poetry-version:
    description: "Poetry version to use"
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      if: ${{ fromJSON(inputs.poetry-install) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        version: ${{ inputs.poetry-version }}
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache }}
