name: "Prepare Python"
description: "Checkout project, set up python"

inputs:
  python_version:
    description: "Python version to use"
    default: "3.11"
  cache:
    description: "Cache type. Supported values: pip, pipenv, poetry"
    default: "poetry"
  install_poetry:
    description: "Install poetry"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      if: ${{ fromJSON(inputs.install_poetry) }} # workaround for composite jobs not being able to pass boolean inputs
      shell: bash
      run: |
        pip install poetry
    - name: Set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{ inputs.python_version }}
        cache: ${{ inputs.cache }}
