name: "End to end test"
description: "Run DIAL end-to-end test"

inputs:
  addons-list-for-tests:
    description: "Dial entities used for listing test"
    type: string
    default: ''
  allure-version:
    type: string
    default: "2.24.0"
  auth-provider:
    description: "Name of authentication provider"
    type: string
    default: "auth0"
  e2e-host:
    required: true
    description: "The host URL for end-to-end testing"
    type: string
  e2e-admin:
    required: true
    description: "Username for admin authentication"
    type: string
  e2e-username:
    required: true
    description: "Comma-separated list of usernames for e2e authentication. Provide enough usernames for all main users, additional users, and second additional users (number of workers * 3)."
    type: string
  e2e-overlay-username:
    required: true
    description: "Comma separated list of usernames for overlay sandbox authentification. The number of users should be equal to number of workers"
    type: string
  e2e-password:
    required: true
    description: "E2E tests password"
    type: string
  e2e-workers:
    description: "Number of threads to run e2e tests"
    type: number
    default: 3
  e2e-overlay-workers:
    description: "Number of threads to run e2e overlay tests"
    type: number
    default: 1
  entity-arithmetic-request-for-api-tests:
    description: "Dial entities used for simple arithmetic API test"
    type: string
    default: ''
  entity-plus-addons-for-api-tests:
    description: "Dial entities used for entity+addons API test"
    type: string
    default: ''
  entity-simple-request-for-api-tests:
    description: "Dial entities used for text request API test, attachment can be expected as a response"
    type: string
    default: ''
  entity-plus-attachment-for-api-tests:
    description: "Dial entities used for attachment request API test"
    type: string
    default: ''
  assistant-plus-addons-for-api-tests:
    description: "Dial entities used for assistant+addons API test"
    type: string
    default: ''
  issue-url:
    description: "Issue URL"
    type: string
    default: ''
  models-list-for-tests:
    description: "Dial entities used for listing test"
    type: string
    default: ''
  next-public-overlay-host:
    required: true
    description: "Overlay domain host"
    type: string
  simple-request-model:
    description: "Model used for simple requests, with or without system prompts, e.g. arithmetic operations, markdown tables generation etc"
    type: string
    default: ''
  test-repository:
    description: "E2E tests Git repository"
    type: string
    default: "epam/ai-dial-chat"
  test-branch:
    description: "E2E tests Git branch"
    type: string
    default: "development"
  tms-url:
    description: "TMS URL"
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.test-repository }}
        ref: ${{ inputs.test-branch }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Install Allure
      run: |
        set -euo pipefail
        curl -fsSL https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz | tar -xzf -
        ./allure-${ALLURE_VERSION}/bin/allure --version
      shell: bash
      env:
        ALLURE_VERSION: ${{ inputs.allure-version }}
    - name: Install playwright
      run: npm install -D @playwright/test
      shell: bash
    - name: Wait for environment
      run: |
        set -euo pipefail
        echo "Expected environment URL ${E2E_HOST}, waiting to be available..."
        ENV_HOSTNAME=$(echo "$E2E_HOST" | awk -F/ '{print $3}')
        curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET https://networkcalc.com/api/dns/lookup/"${ENV_HOSTNAME}"
        curl --retry 30 --retry-delay 10 --retry-all-errors --fail --insecure --no-progress-meter --location --head -o /dev/null -w "%{http_code}\n" -X GET "${E2E_HOST}"/api/health
      shell: bash
      env:
        E2E_HOST: ${{ inputs.e2e-host }}
    - name: Run tests
      run: |
        set -euo pipefail
        echo "Host to run e2e tests ${E2E_HOST}"
        echo "Host to run overlay e2e tests ${NEXT_PUBLIC_OVERLAY_HOST}"
        echo "Config for arithmetic e2e api tests ${ENTITY_ARITHMETIC_REQUEST_FOR_API_TESTS}"
        echo "Config for attachment request e2e api tests ${ENTITY_PLUS_ATTACHMENT_FOR_API_TESTS}"
        echo "Config for attachment response e2e api tests ${ENTITY_SIMPLE_REQUEST_FOR_API_TESTS}"
        echo "Simple requests model for e2e tests ${SIMPLE_REQUEST_MODEL}"
        npm run e2e:ci
      shell: bash
      env:
        PLAYWRIGHT_NAVIGATION_TIMEOUT: 60000
        PLAYWRIGHT_ACTION_TIMEOUT: 60000
        PLAYWRIGHT_EXPECT_TIMEOUT: 60000
        TMS_URL: ${{ inputs.tms-url }}
        ISSUE_URL: ${{ inputs.issue-url }}
        E2E_HOST: ${{ inputs.e2e-host }}
        E2E_ADMIN: ${{ inputs.e2e-admin }}
        E2E_USERNAME: ${{ inputs.e2e-username }}
        E2E_OVERLAY_USERNAME: ${{ inputs.e2e-overlay-username }}
        E2E_PASSWORD: ${{ inputs.e2e-password }}
        E2E_WORKERS: ${{ inputs.e2e-workers }}
        E2E_OVERLAY_WORKERS: ${{ inputs.e2e-overlay-workers }}
        NEXT_PUBLIC_OVERLAY_HOST: ${{ inputs.next-public-overlay-host }}
        AUTH_PROVIDER: ${{ inputs.auth-provider }}
        ENTITY_ARITHMETIC_REQUEST_FOR_API_TESTS: ${{ inputs.entity-arithmetic-request-for-api-tests }}
        ENTITY_PLUS_ADDONS_FOR_API_TESTS: ${{ inputs.entity-plus-addons-for-api-tests }}
        ENTITY_SIMPLE_REQUEST_FOR_API_TESTS: ${{ inputs.entity-simple-request-for-api-tests }}
        ENTITY_PLUS_ATTACHMENT_FOR_API_TESTS: ${{ inputs.entity-plus-attachment-for-api-tests }}
        ASSISTANT_PLUS_ADDONS_FOR_API_TESTS: ${{ inputs.assistant-plus-addons-for-api-tests }}
        MODELS_LIST_FOR_TESTS: ${{ inputs.models-list-for-tests }}
        ADDONS_LIST_FOR_TESTS: ${{ inputs.addons-list-for-tests }}
        SIMPLE_REQUEST_MODEL: ${{ inputs.simple-request-model }}
    - name: Generate Allure Chat Report
      run: ./allure-${ALLURE_VERSION}/bin/allure generate ./apps/chat-e2e/allure-chat-results -o ./apps/chat-e2e/allure-chat-report --clean
      shell: bash
      env:
        ALLURE_VERSION: ${{ inputs.allure-version }}
    - name: Generate Allure Overlay Report
      run: ./allure-${ALLURE_VERSION}/bin/allure generate ./apps/chat-e2e/allure-overlay-results -o ./apps/chat-e2e/allure-overlay-report --clean
      shell: bash
      env:
        ALLURE_VERSION: ${{ inputs.allure-version }}
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: |
          apps/chat-e2e/allure-chat-report
          apps/chat-e2e/allure-overlay-report
        retention-days: 30
