name: "Prepare python"
description: "Checkout project, set up python"
inputs:
  python_version:
    description: "Python version to use"
    required: false
    default: "3.11"
  install_poetry:
    description: "Install poetry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: ${{ inputs.python_version }}
        #cache: 'pip'
    - name: Install poetry
      if: ${{ inputs.install_poetry == 'true' }}
      shell: bash
      run: |
        pip install poetry
