name: 'Generate release notes'
description: 'Generate release notes based on conventional commits'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      with:
        fetch-depth: 0
        fetch-tags: true
        lfs: true
    - uses: epam/ai-dial-ci/actions/prepare_python@feat/test-ci
    - name: Generate changelog
      id: generate_changelog
      shell: bash
      run: |
        set -x
        pip install auto-changelog
        
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null|| echo NO )

        if [[ "${LAST_TAG}" == "NO" ]]; then
            git log  --pretty=format:"%s" 
        
        else
            git log "${LAST_TAG}"..HEAD --pretty=format:"%s" > /tmp/my_commits_log_all
        fi
    
        auto-changelog --github --stdout -u --debug > /tmp/my_changelog
        
        echo "debug-------"
        cat /tmp/my_changelog
        echo "debug-------"
        
        {
          echo "CHANGELOG<<EOF"
          cat /tmp/my_changelog
          echo "EOF"
        } >> "$GITHUB_ENV"