name: "ORT scan"
description: "Run Opensource Review Toolkit scan"
inputs:
  bypass_checks:
    description: "Do not fail pipeline if checks failed"
    default: "false"
  allow_dynamic_versions:
    description: "Allow dynamic versions"
    default: "true"
  fail_on:
    description: "Comma-separated list of ORT results that if exceeding their severity threshold will fail the action. Accepted values are '', 'issues', 'violations' or 'issues,violations'."
    default: "violations"
  analyze_args:
    description: "Arguments to pass to analyze command"
    default: ""
  cli_args:
    description: "List of arguments to pass to ORT CLI, applies to all commands."
    default: "-P ort.forceOverwrite=true --stacktrace"

runs:
  using: "composite"
  steps:
    - name: Run GitHub Action for ORT
      uses: oss-review-toolkit/ort-ci-github-action@9acdf1e56f1b42972b12274ae56c35bf70a5f65b # v1.0.1
      with:
        allow-dynamic-versions: ${{ inputs.allow_dynamic_versions }}
        fail-on: ${{ inputs.fail_on }}
        ort-cli-analyze-args: ${{ inputs.analyze_args || '' }}
        ort-cli-args: ${{ inputs.cli_args || '' }}
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass_checks }} # Hack to use the input below as a boolean
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
