name: "Prepare Java"
description: "Set up Java with Gradle"

inputs:
  java_version:
    description: "Java version to use"
    default: "17"
  java_distribution:
    description: "Java distribution to use"
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
        # Not using `cache: gradle` because `setup-gradle` action takes care of it
        # ref: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#incompatibility-with-other-caching-mechanisms
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
      with:
        add-job-summary: "on-failure"
