name: "Prepare Java"
description: "Set up Java with Gradle cache"

inputs:
  java_version:
    description: "Java version to use"
    default: "17"
  java_distribution:
    description: "Java distribution to use"
    default: "temurin"
  cache:
    description: "Cache type. Supported values: maven, gradle, sbt"
    default: "gradle"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
        cache: ${{ inputs.cache }}
