name: "Prepare Java"
description: "Set up Java with Gradle"

inputs:
  java_version:
    description: "Java version to use"
    default: "17"
  java_distribution:
    description: "Java distribution to use"
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
        # Not using `cache: gradle` because `setup-gradle` action takes care of it
        # ref: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#incompatibility-with-other-caching-mechanisms
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
      with:
        add-job-summary: "on-failure"
