name: "Prepare Java"
description: "Set up Java with Gradle"

inputs:
  java_version:
    description: "Java version to use"
    default: "17"
  java_distribution:
    description: "Java distribution to use"
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
        # Not using `cache: gradle` because `setup-gradle` action takes care of it
        # ref: https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#incompatibility-with-other-caching-mechanisms
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
      with:
        add-job-summary: "on-failure"
