name: "Prepare JDK"
description: "Checkout project, set up JDK, prepare gradle caches"
inputs:
  java_version:
    description: "Java version to use"
    required: false
    default: "17"
  java_distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"
  cache_path:
    description: "Path to cache"
    required: false
    default: "~/.gradle/caches"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        lfs: true
    - name: Set up JDK
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
    - name: Cache gradle dependencies
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: ${{ inputs.cache_path }}
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-
