name: "Build docker"
description: "Build a docker image, tag it, (optionally) scan it, and (optionally) push it to Dockerhub and GHCR"
inputs:
  bypass_checks:
    description: "Do not fail pipeline if checks failed"
    default: "false"
  push:
    description: "Push the image to the registry"
    required: false
    default: "false"
  scan:
    description: "Scan with Trivy"
    required: false
    default: "true"
  scan_severity:
    description: "Severity of vulnerabilities to fail the build"
    required: false
    default: "CRITICAL,HIGH"
  scan_vuln_type:
    description: "Type of vulnerabilities to scan"
    required: false
    default: "os,library"
  scan_ignore_unfixed:
    description: "Ignore unpatched/unfixed vulnerabilities"
    required: false
    default: "true"
  image_name:
    description: "Name of the image to build"
    required: true
  image_tag:
    description: "Tag of the image to build"
    required: true
  image_extra_aliases:
    description: "Extra aliases for the image, e.g. to publish to multiple registries"
    required: false
    default: ""
  ghcr_username:
    description: "GitHub Container Registry username"
    required: false
    default: ""
  ghcr_password:
    description: "GitHub Container Registry password"
    required: false
    default: ""
  dockerhub_username:
    description: "Docker Hub username"
    required: false
    default: ""
  dockerhub_password:
    description: "Docker Hub password"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      if: ${{ fromJSON(inputs.push) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.ghcr_password }}
    - name: Login to Docker Hub
      if: ${{ fromJSON(inputs.push) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    - name: Build and export to Docker
      if: ${{ fromJSON(inputs.scan) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
      with:
        context: .
        load: true
        tags: |
          ${{ inputs.image_name }}:${{ inputs.image_tag }}
          ${{ inputs.image_extra_aliases }}
        labels: |
          maintainer=AI DIAL
          org.opencontainers.image.title=${{ inputs.image_name }}
          org.opencontainers.image.version=${{ inputs.image_tag }}
          org.opencontainers.image.description=${{ inputs.image_name }}
          org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
    - name: Run Trivy vulnerability scanner (stdout, table view, no fail)
      if: ${{ fromJSON(inputs.scan) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # v0.28.0
      with:
        image-ref: "${{ inputs.image_name }}:${{ inputs.image_tag }}"
        format: "table"
        ignore-unfixed: ${{ inputs.scan_ignore_unfixed }}
        vuln-type: ${{ inputs.scan_vuln_type }}
        severity: ${{ inputs.scan_severity }}
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass_checks }} # Hack to use the input below as a boolean
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Run Trivy vulnerability scanner (SARIF, may fail)
      # Do not perform SARIF scan on private repos - GitHub Advanced Security is not enabled
      if: ${{ fromJSON(inputs.scan) && !github.event.repository.private }} # workaround for composite jobs not being able to pass boolean inputs
      uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # v0.28.0
      with:
        image-ref: "${{ inputs.image_name }}:${{ inputs.image_tag }}"
        format: "sarif"
        output: "trivy-results.sarif"
        exit-code: "1"
        ignore-unfixed: ${{ inputs.scan_ignore_unfixed }}
        vuln-type: ${{ inputs.scan_vuln_type }}
        severity: ${{ inputs.scan_severity }}
        limit-severities-for-sarif: true
        skip-setup-trivy: true  # We already have trivy installed just above
      env:
        TRIVY_SKIP_DB_UPDATE: true # We already have the DB updated just above
        TRIVY_SKIP_JAVA_DB_UPDATE: true # We already have the Java DB updated just above
        CONTINUE_ON_ERROR: ${{ inputs.bypass_checks }} # Hack to use the input below as a boolean
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Upload Trivy scan results to GitHub Security tab
      # Do not upload SARIF reports on private repos - GitHub Advanced Security is not enabled
      if: ${{ !cancelled() && fromJSON(inputs.scan) && !github.event.repository.private }} # workaround for composite jobs not being able to pass boolean inputs
      uses: github/codeql-action/upload-sarif@396bb3e45325a47dd9ef434068033c6d5bb0d11a #v3.27.3
      with:
        sarif_file: "trivy-results.sarif"
        category: trivy
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass_checks }} # Hack to use the input below as a boolean
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Build and push
      if: ${{ fromJSON(inputs.push) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.image_name }}:${{ inputs.image_tag }}
          ${{ inputs.image_extra_aliases }}
        labels: |
          maintainer=AI DIAL
          org.opencontainers.image.title=${{ inputs.image_name }}
          org.opencontainers.image.version=${{ inputs.image_tag }}
          org.opencontainers.image.description=${{ inputs.image_name }}
          org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
