name: "Build docker"
description: "Build a docker image, tag it, (optionally) scan it, and (optionally) push it to Dockerhub and GHCR"
inputs:
  bypass_checks:
    description: "Do not fail pipeline if checks failed"
    default: "false"
  push:
    description: "Push the image to the registry"
    required: false
    default: "false"
  scan:
    description: "Scan with Trivy"
    required: false
    default: "true"
  scan_severity:
    description: "Severities of vulnerabilities to fail the build"
    required: false
    default: "CRITICAL,HIGH"
  scan_severity_for_sarif:
    description: "Severities of vulnerabilities in SARIF report"
    required: false
    default: "CRITICAL,HIGH"
  scan_limit_severities_for_sarif:
    description: "Limit severities for SARIF format"
    required: false
    default: "true"
  scan_vuln_type:
    description: "Type of vulnerabilities to scan"
    required: false
    default: "os,library"
  scan_ignore_unfixed:
    description: "Ignore unpatched/unfixed vulnerabilities"
    required: false
    default: "true"
  image_name:
    description: "Name of the image to build"
    required: true
  image_tag:
    description: "Tag of the image to build"
    required: true
  image_extra_aliases:
    description: "Extra aliases for the image, e.g. to publish to multiple registries"
    required: false
    default: ""
  ghcr_username:
    description: "GitHub Container Registry username"
    required: false
    default: ""
  ghcr_password:
    description: "GitHub Container Registry password"
    required: false
    default: ""
  dockerhub_username:
    description: "Docker Hub username"
    required: false
    default: ""
  dockerhub_password:
    description: "Docker Hub password"
    required: false
    default: ""
  gpr_username:
    required: false
    default: ${{ github.actor }}
  gpr_password:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
    - name: Login to GitHub Container Registry
      if: ${{ fromJSON(inputs.push) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.ghcr_password }}
    - name: Login to Docker Hub
      if: ${{ fromJSON(inputs.push) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    - name: Build and export to Docker
      if: ${{ fromJSON(inputs.scan) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
      with:
        context: .
        load: true
        tags: |
          ${{ inputs.image_name }}:${{ inputs.image_tag }}
          ${{ inputs.image_extra_aliases }}
        labels: |
          maintainer=AI DIAL
          org.opencontainers.image.title=${{ inputs.image_name }}
          org.opencontainers.image.version=${{ inputs.image_tag }}
          org.opencontainers.image.description=${{ inputs.image_name }}
          org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
        secrets: |
          GPR_USERNAME=${{ inputs.gpr_username }}
          GPR_PASSWORD=${{ inputs.gpr_password }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
    - name: Run Trivy vulnerability scanner (SARIF, no fail)
      # Do not perform SARIF scan on private repos - GitHub Advanced Security is not enabled
      if: ${{ fromJSON(inputs.scan) && !github.event.repository.private }} # workaround for composite jobs not being able to pass boolean inputs
      uses: aquasecurity/trivy-action@7aca5acc9500b463826cc47a47a65ad7d404b045 # TODO: v0.31.0+
      with:
        image-ref: "${{ inputs.image_name }}:${{ inputs.image_tag }}"
        format: "sarif"
        exit-code: "0"
        output: "trivy-results.sarif"
        ignore-unfixed: ${{ inputs.scan_ignore_unfixed }}
        vuln-type: ${{ inputs.scan_vuln_type }}
        severity: ${{ inputs.scan_severity_for_sarif }}
        limit-severities-for-sarif: ${{ inputs.scan_limit_severities_for_sarif }}
      env:
        TRIVY_DISABLE_VEX_NOTICE: true
      continue-on-error: true # Alongside with `exit-code: 0`, ensure not failing the workflow
    - name: Upload Trivy scan results to GitHub Security tab
      # Do not upload SARIF reports on private repos - GitHub Advanced Security is not enabled
      if: ${{ !cancelled() && fromJSON(inputs.scan) && !github.event.repository.private }} # workaround for composite jobs not being able to pass boolean inputs
      uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 #v3.28.15
      with:
        sarif_file: "trivy-results.sarif"
        category: trivy
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass_checks }} # Hack to use the input below as a boolean
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Run Trivy vulnerability scanner (stdout, table view, may fail)
      if: ${{ fromJSON(inputs.scan) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: aquasecurity/trivy-action@7aca5acc9500b463826cc47a47a65ad7d404b045 # TODO: v0.31.0+
      with:
        image-ref: "${{ inputs.image_name }}:${{ inputs.image_tag }}"
        format: "table"
        exit-code: "1"
        ignore-unfixed: ${{ inputs.scan_ignore_unfixed }}
        vuln-type: ${{ inputs.scan_vuln_type }}
        severity: ${{ inputs.scan_severity }}
        skip-setup-trivy: true # We already have trivy installed just above
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass_checks }} # Hack to use the input below as a boolean
        TRIVY_SKIP_DB_UPDATE: true # We already have the DB updated just above
        TRIVY_SKIP_JAVA_DB_UPDATE: true # We already have the Java DB updated just above
        TRIVY_DISABLE_VEX_NOTICE: true
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Build and push
      if: ${{ fromJSON(inputs.push) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.image_name }}:${{ inputs.image_tag }}
          ${{ inputs.image_extra_aliases }}
        labels: |
          maintainer=AI DIAL
          org.opencontainers.image.title=${{ inputs.image_name }}
          org.opencontainers.image.version=${{ inputs.image_tag }}
          org.opencontainers.image.description=${{ inputs.image_name }}
          org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
        secrets: |
          GPR_USERNAME=${{ inputs.gpr_username }}
          GPR_PASSWORD=${{ inputs.gpr_password }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
