name: Build docker
description: Build a docker image, tag it, (optionally) scan it, and (optionally) push it to Dockerhub and GHCR
inputs:
  bypass-checks:
    description: Do not fail pipeline if checks failed
    default: "false"
  push-enabled:
    description: Push the image to registry(ies)
    default: "false"
  trivy-enabled:
    description: Enable Trivy scanning
    default: "true"
  trivy-severity:
    description: Severities of vulnerabilities to fail the build
    default: "CRITICAL,HIGH"
  trivy-severity-for-sarif:
    description: Severities of vulnerabilities in SARIF report
    default: "CRITICAL,HIGH"
  trivy-limit-severities-for-sarif:
    description: By default SARIF format enforces output of all vulnerabilities regardless of configured severities. To override this behavior set this parameter to true and specify desired severities in the `trivy-severity-for-sarif` parameter
    default: "true"
  trivy-vuln-type:
    description: Type of vulnerabilities to scan
    default: "os,library"
  trivy-scanners:
    description: Comma-separated list of what security issues to detect
    default: "vuln,secret"
  trivy-ignore-unfixed:
    description: Ignore unpatched/unfixed vulnerabilities
    default: "true"
  image-name:
    description: Name of the image to build
    required: true
  image-tag:
    description: Tag of the image to build
    required: true
  image-extra-aliases:
    description: Extra aliases for the image, e.g. to publish to multiple registries
    default: ""
  ghcr-username:
    description: GitHub Container Registry username. This is required for pushing to GitHub Container Registry
    default: ${{ github.actor }}
  ghcr-password:
    description: GitHub Container Registry password/token. This is required for pushing to GitHub Container Registry
    default: ""
  dockerhub-username:
    description: Docker Hub username. This is required for pushing to Docker Hub
    default: ""
  dockerhub-password:
    description: Docker Hub password/token. This is required for pushing to Docker Hub
    default: ""
  gpr-username:
    description: GitHub Package Registry username (for pulling packages from image being built)
    default: ${{ github.actor }}
  gpr-password:
    description: GitHub Package Registry password/token (for pulling packages from image being built)
    default: ""
  platforms:
    description: Docker build platforms
    default: "linux/amd64"
  dockerfile-path:
    description: Path to the Dockerfile
    default: "Dockerfile"

runs:
  using: "composite"
  steps:
    - name: Setup Docker Qemu
      if: ${{ inputs.platforms != 'linux/amd64' }}
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
    - name: Login to GitHub Container Registry
      if: ${{ fromJSON(inputs.push-enabled) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr-username }}
        password: ${{ inputs.ghcr-password }}
    - name: Login to Docker Hub
      if: ${{ fromJSON(inputs.push-enabled) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
    - name: Build and export to Docker
      if: ${{ fromJSON(inputs.trivy-enabled) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        load: true
        platforms: linux/amd64
        tags: |
          ${{ inputs.image-name }}:${{ inputs.image-tag }}
          ${{ inputs.image-extra-aliases }}
        labels: |
          maintainer=AI DIAL
          org.opencontainers.image.title=${{ inputs.image-name }}
          org.opencontainers.image.version=${{ inputs.image-tag }}
          org.opencontainers.image.description=${{ inputs.image-name }}
          org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
        secrets: |
          GPR_USERNAME=${{ inputs.gpr-username }}
          GPR_PASSWORD=${{ inputs.gpr-password }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
    - name: Run Trivy scanner (JSON output, no fail)
      id: trivy
      if: ${{ fromJSON(inputs.trivy-enabled) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
      with:
        image-ref: "${{ inputs.image-name }}:${{ inputs.image-tag }}"
        format: "json"
        exit-code: "0" # Do not fail on findings here, should be handled in the latest "trivy convert" step
        output: "trivy-results.json"
        ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
        vuln-type: ${{ inputs.trivy-vuln-type }}
        scanners: ${{ inputs.trivy-scanners }}
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass-checks }} # Hack to use the input below as a boolean
        TRIVY_DISABLE_VEX_NOTICE: true
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Generate Trivy report (SARIF)
      id: trivy-generate-sarif
      # Do not generate SARIF reports on private repos - GitHub Advanced Security is not enabled
      # Do not generate SARIF reports for pull requests from forks
      if: ${{ steps.trivy.outcome == 'success' && !github.event.repository.private && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name) }}
      run: |
        trivy convert --format sarif --output trivy-results.sarif --exit-code 0 trivy-results.json
      shell: bash
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass-checks }} # Hack to use the input below as a boolean
        TRIVY_SCANNERS: ${{ inputs.trivy-scanners }}
        TRIVY_SEVERITY: ${{ fromJson(inputs.trivy-limit-severities-for-sarif) && inputs.trivy-severity-for-sarif || '' }}
        TRIVY_DISABLE_VEX_NOTICE: true
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Upload Trivy report (SARIF)
      if: ${{ steps.trivy-generate-sarif.outcome == 'success' }}
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: "trivy-results.sarif"
        category: trivy
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass-checks }} # Hack to use the input below as a boolean
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Generate Trivy report (Table, must fail on findings)
      if: ${{ steps.trivy.outcome == 'success' }}
      run: |
        trivy convert --format table --exit-code 1 trivy-results.json
      shell: bash
      env:
        CONTINUE_ON_ERROR: ${{ inputs.bypass-checks }} # Hack to use the input below as a boolean
        TRIVY_SCANNERS: ${{ inputs.trivy-scanners }}
        TRIVY_SEVERITY: ${{ inputs.trivy-severity }}
        TRIVY_DISABLE_VEX_NOTICE: true
      continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
    - name: Build and push
      if: ${{ fromJSON(inputs.push-enabled) }} # workaround for composite jobs not being able to pass boolean inputs
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        platforms: ${{ inputs.platforms }}
        tags: |
          ${{ inputs.image-name }}:${{ inputs.image-tag }}
          ${{ inputs.image-extra-aliases }}
        labels: |
          maintainer=AI DIAL
          org.opencontainers.image.title=${{ inputs.image-name }}
          org.opencontainers.image.version=${{ inputs.image-tag }}
          org.opencontainers.image.description=${{ inputs.image-name }}
          org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
          org.opencontainers.image.licenses=Apache-2.0
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
        secrets: |
          GPR_USERNAME=${{ inputs.gpr-username }}
          GPR_PASSWORD=${{ inputs.gpr-password }}
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
