name: Publish Git Tag and Release

description: Commit changes back to git, apply tag and create release

inputs:
  extra-commit-command:
    description: Extra command to commit changes, e.g. `git add version.txt ; git commit -m "[skip ci] Update version" || true`
    default: ""
  tag-version:
    description: Tag version
    required: true
  changelog-file:
    description: Changelog file
    required: true
  artifacts:
    description: Artifacts to upload
    default: ""
  draft-stable-releases:
    description: Create stable GitHub releases as drafts
    default: "false"
  git-user-name:
    description: Git user name for committing changes
    default: "github-actions[bot]"
  git-user-email:
    description: Git user email for committing changes
    default: "41898282+github-actions[bot]@users.noreply.github.com"

runs:
  using: "composite"
  steps:
    - name: Commit and push changes
      run: |
        set -x

        ${{ inputs.extra-commit-command }}

        git tag -a "${{ inputs.tag-version }}" -m "$(cat ${{ inputs.changelog-file }})"

        git push
        git push --tags
      env:
        GIT_AUTHOR_NAME: ${{ inputs.git-user-name }}
        GIT_AUTHOR_EMAIL: ${{ inputs.git-user-email }}
        GIT_COMMITTER_NAME: ${{ inputs.git-user-name }}
        GIT_COMMITTER_EMAIL: ${{ inputs.git-user-email }}
      shell: bash
    - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      with:
        artifacts: ${{ inputs.artifacts }}
        bodyFile: ${{ inputs.changelog-file }}
        allowUpdates: true
        updateOnlyUnreleased: true
        omitDraftDuringUpdate: true
        draft: ${{ fromJSON(inputs.draft-stable-releases) && !contains(inputs.tag-version, '-') }} # draft if it's a stable release and the input is 'true'
        prerelease: ${{ contains(inputs.tag-version, '-') }} # will capture e.g. `-rc`
        makeLatest: ${{ contains(inputs.tag-version, '-') && 'false' || 'legacy' }} # false if it's a pre-release, otherwise let GitHub decide (based on semver)
        tag: ${{ inputs.tag-version }}
