name: "Publish git tag and release"
description: "Commit changes back to git, apply tag and create release"
inputs:
  extra-commit-command:
    description: 'Extra command to commit changes, e.g. `git add version.txt ; git commit -m "[skip ci] Update version" || true`'
    required: false
    default: ""
  tag-version:
    description: "Tag version"
    required: true
  changelog-file:
    description: "Changelog file"
    required: true
  artifacts:
    description: "Artifacts to upload"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Commit and push changes
      shell: bash
      run: |
        set -x
        git config --global user.name "ai-dial-actions"
        git config --global user.email "149404362+ai-dial-actions@users.noreply.github.com"

        ${{ inputs.extra-commit-command }}

        CURRENT_BRANCH=$(git symbolic-ref -q HEAD)
        CURRENT_BRANCH=${CURRENT_BRANCH##refs/heads/}
        CURRENT_BRANCH=${CURRENT_BRANCH:-HEAD}
        if [[ "$CURRENT_BRANCH" =~ "release-" ]]; then
          git tag -a "${{ inputs.tag-version }}" -m "$(cat ${{ inputs.changelog-file }})"
        fi

        git push
        git push --tags

    - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
      if: github.ref != 'refs/heads/development'
      with:
        artifacts: ${{ inputs.artifacts }}
        bodyFile: ${{ inputs.changelog-file }}
        allowUpdates: true
        updateOnlyUnreleased: true
        makeLatest: true
        draft: true
        tag: ${{ inputs.tag-version }}
