name: Destroy Review Environment on PR Merge

on:
  repository_dispatch:
    types: [cleanup-review-environment]

jobs:
  destroy-gitlab-environment:
    name: Destroy GitLab Review Environment
    runs-on: ubuntu-latest
    environment:
      name: e2e-test
    outputs:
      github-app: ${{ github.event.client_payload.github-app }}
      github-pr: ${{ github.event.client_payload.github-pr }}

    steps:
      - name: Destroy review environment on PR merge
        env:
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}
          GITHUB_REPO: ${{ github.repository }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN_TEST_DESTROY }}
        shell: bash  
        run: |
          # Remove "epam/" prefix from the repository name to match the GitLab environment name
          GITHUB_REPO=${GITHUB_REPO:5}

          # Get environment data
          ENV_DATA=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
            --url "https://gitlab.deltixhub.com/api/v4/projects/1779/environments?name=$GITHUB_REPO/pr-$GITHUB_PR_ID")

          # Check if review environment exists
          if [ -z "$ENV_DATA" ]; then
            echo "Review environment hasn't been created"
            exit 0 
          fi
          
          # Get environment current state
          CURRENT_ENV_STATE=$(echo "$ENV_DATA" | jq -r '.[0].state')   
          echo "Current review environment status is ${CURRENT_ENV_STATE}"
          
          if [ "$CURRENT_ENV_STATE" = "stopped" ]; then
            exit 0 
          elif [ "$CURRENT_ENV_STATE" = "available" ]; then
            # Get the environment id base on the environment name
            GITLAB_ENV_ID=$(echo "$ENV_DATA" | jq -r '.[0].id')
            echo "Gitlab review environment id: ${GITLAB_ENV_ID}" 

            echo "Stopping review environment... " 

            #stop the environment based on the environment id
            curl -s --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
              --url "https://gitlab.deltixhub.com/api/v4/projects/1779/environments/${GITLAB_ENV_ID}/stop" 
              
            #Confirm is review environment is stopped
            while [ "$CURRENT_ENV_STATE" != "stopped" ]
            do
                echo "Waiting for environment to stop..."
                sleep 60
                CURRENT_ENV_STATE=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
                  --url "https://gitlab.deltixhub.com/api/v4/projects/1779/environments?name=$GITHUB_REPO/pr-$GITHUB_PR_ID" \
                  | jq -r '.[0].state')
            done
                echo "Environment stopped successfully."            
          fi
