name: Destroy GitLab Environment on PR Merge

on:
  pull_request:
    types:
      - closed
    inputs:
      runs-on:
        type: string
        description: Overrides jobs runs-on settings (json-encoded list)
        default: '["ubuntu-24.04"]'

jobs:
  destroy-gitlab-environment:
    name: Destroy GitLab Review Environment
    # Only run when PR is actually merged, not just closed
    if: github.event.pull_request.merged == false ### temporary use for not merging
    runs-on: ${{ fromJSON(inputs.runs-on) }}

    steps:
      - name: Extract PR Number
        env:
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}
          GITHUB_REPO: ${{ github.repository }}
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN_TEST_DESTROY }}
        shell: bash  
        run: |
          echo "$GITHUB_PR_ID"
          # remove "epam/" prefix from the repository name to match the GitLab environment name
          $GITHUB_REPO=${GITHUB_REPO:5}
          echo "$GITHUB_REPO"

          #get the environment id base on the environment name
          GITLAB_ENV_ID=$(curl --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
            --url "https://gitlab.deltixhub.com/api/v4/projects/1779/environments?name=$GITHUB_REPO/pr-$GITHUB_PR_ID" \
            | jq -r '.[0].id')

          echo "$GITLAB_ENV_ID"  

          #stop the environment based on the environment id
          STATE=$(curl --request POST \
            --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
            --url "https://gitlab.deltixhub.com/api/v4/projects/1779/environments/${GITLAB_ENV_ID}/stop" \
            | jq -r '.state')

          echo "Review environment for repostory epam/$GITHUB_REPO pr-$GITHUB_PR_ID has been$STATE"
