name: Run e2e-tests

on:
  repository_dispatch:
    types: [e2e-tests-workflow]

jobs:
  deploy-env:
    runs-on: ubuntu-latest
    outputs:
      github-app: ${{ github.event.client_payload.github-app }}
      github-sha: ${{ steps.sha.outputs.SHA }}
    steps:
      - name: Obtain short sha
        id: sha
        shell: bash
        env:
          TRIGGER_GITHUB_SHA: ${{ github.event.client_payload.github-sha}}
        run: |
          # shorten the commit SHA to the first 7 characters
          echo "SHA=${TRIGGER_GITHUB_SHA:0:7}" >>$GITHUB_OUTPUT
      - name: Deploy environment
        id: deploy
        uses: digital-blueprint/gitlab-pipeline-trigger-action@7fef6b4967aef68a1671ccf42a6e45f7a27487d8 # v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          trigger_token: ${{ secrets.E2E_DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.E2E_DEPLOY_ACCESS_TOKEN }}
          id: ${{ github.event.client_payload.gitlab-project-id }}
          ref: ${{ github.event.client_payload.gitlab-project-ref || vars.E2E_DEPLOY_REF }}
          variables: >
            {
              "TRIGGER_GITHUB_APP":"${{ github.event.client_payload.github-app }}",
              "TRIGGER_GITHUB_SHA": "${{ steps.sha.outputs.SHA }}",
              "GITHUB_STAGE": "deploy"
            }

  e2e-test:
    uses: epam/ai-dial-ci/.github/workflows/gh-e2e-test.yml@2.4.0
    needs:
      - deploy-env
    with:
      allure-report-prefix: "${{ needs.deploy-env.outputs.github-app }}-${{ needs.deploy-env.outputs.github-sha }}"
      e2e-host: "https://chat-${{ needs.deploy-env.outputs.github-app }}-${{ needs.deploy-env.outputs.github-sha }}.nightly-test.deltixhub.io"
      next-public-overlay-host: "https://overlay-${{ needs.deploy-env.outputs.github-app }}-${{ needs.deploy-env.outputs.github-sha }}.nightly-test.deltixhub.io"
    secrets:
      E2E_ADMIN: ${{ secrets.E2E_ADMIN }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_OVERLAY_USERNAME: ${{ secrets.E2E_OVERLAY_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
      NEXT_PUBLIC_OVERLAY_USER_BUCKET: ${{ secrets.NEXT_PUBLIC_OVERLAY_USER_BUCKET }}

  destroy-env:
    runs-on: ubuntu-latest
    needs:
      - deploy-env
      - e2e-test
    if: always()
    steps:
      - name: Destroy environment
        id: destroy
        uses: digital-blueprint/gitlab-pipeline-trigger-action@7fef6b4967aef68a1671ccf42a6e45f7a27487d8 # v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          trigger_token: ${{ secrets.E2E_DEPLOY_TRIGGER_TOKEN }}
          access_token: ${{ secrets.E2E_DEPLOY_ACCESS_TOKEN }}
          id: ${{ github.event.client_payload.gitlab-project-id }}
          ref: ${{ github.event.client_payload.gitlab-project-ref || vars.E2E_DEPLOY_REF }}
          variables: >
            {
              "TRIGGER_GITHUB_APP":"${{ needs.deploy-env.outputs.github-app }}",
              "TRIGGER_GITHUB_SHA": "${{ needs.deploy-env.outputs.github-sha }}",
              "GITHUB_STAGE": "destroy"
            }
