name: Release version

on:
  workflow_call:
    inputs:
      bypass_checks:
        type: boolean
        default: false
        description: Do not fail pipeline if checks failed
      python_version:
        type: string
        default: '3.11'
        description: Python version to use

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  style_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: epam/ai-dial-ci/actions/prepare_python@feat/test-ci
        with:
          python_version: ${{ inputs.python_version }}
      - name: Test
        continue-on-error: ${{ inputs.bypass_checks }}
        run: |
          make lint

  code_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: epam/ai-dial-ci/actions/prepare_python@feat/test-ci
        with:
          python_version: ${{ inputs.python_version }}
      - name: Test
        continue-on-error: ${{ inputs.bypass_checks }}
        run: |
          make test

  calculate_version:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.semantic_versioning.outputs.next_version }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: epam/ai-dial-ci/actions/semantic_versioning@feat/test-ci
        id: semantic_versioning

  release:
    needs: calculate_version
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      contents: write
      packages: write

    steps:
      - uses: epam/ai-dial-ci/actions/generate_release_notes@feat/test-ci
      - uses: epam/ai-dial-ci/actions/prepare_python@feat/test-ci
        with:
          python_version: ${{ inputs.python_version }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc #v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: epam/ai-dial-ci/actions/build_docker@feat/test-ci
        with:
          image_name: ghcr.io/${{ env.IMAGE_NAME }}
          image_tag: ${{ needs.calculate_version.outputs.next_version }}
          push: true
          scan: false
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v1
        with:
          target_commitish: ${{ github.sha }}
          tag_name: ${{ needs.calculate_version.outputs.next_version }}
          body: |
            # ${{ needs.calculate_version.outputs.next_version }}

            ${{ env.CHANGELOG }}