name: Python Package PR workflow

on:
  workflow_call:
    inputs:
      bypass-checks:
        type: boolean
        default: false
        description: Do not fail pipeline if checks failed
      style-checks-enabled:
        type: boolean
        default: true
        description: Enable style_checks
      style-checks-bypassed:
        type: boolean
        default: false
        description: Do not fail pipeline if style_checks failed
      code-checks-enabled:
        type: boolean
        default: true
        description: Enable code_checks
      code-checks-bypassed:
        type: boolean
        default: false
        description: Do not fail pipeline if code_checks failed
      code-checks-python-versions:
        type: string
        description: Python versions to run tests against
        default: '["3.8", "3.9", "3.10", "3.11"]'
      ort-enabled:
        type: boolean
        default: true
        description: Enable ORT scanning
      ort-bypassed:
        type: boolean
        default: false
        description: Do not fail pipeline if ORT scan failed
      ort-version:
        type: string
        default: "latest"
        description: ORT version to use
      trivy-enabled:
        type: boolean
        default: true
        description: Enable Trivy scanning
      trivy-bypassed:
        type: boolean
        default: false
        description: Do not fail pipeline if Trivy failed
      trivy-severity:
        type: string
        default: "CRITICAL,HIGH"
        description: Severities of vulnerabilities to fail the build
      trivy-severity-for-sarif:
        type: string
        default: "CRITICAL,HIGH"
        description: "Severities of vulnerabilities in SARIF report"
      trivy-limit-severities-for-sarif:
        type: boolean
        default: true
        description: Limit severities for SARIF format
      python-version:
        type: string
        default: "3.11"
        description: Python version to use
      poetry-version:
        type: string
        description: "Poetry version to use"
        default: "1.8.5"

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    uses: ./.github/workflows/python_package_test.yml
    with:
      bypass-checks: ${{ inputs.bypass-checks }}
      style-checks-enabled: ${{ inputs.style-checks-enabled }}
      style-checks-bypassed: ${{ inputs.style-checks-bypassed }}
      code-checks-enabled: ${{ inputs.code-checks-enabled }}
      code-checks-bypassed: ${{ inputs.code-checks-bypassed }}
      code-checks-python-versions: ${{ inputs.code-checks-python-versions }}
      ort-enabled: ${{ inputs.ort-enabled }}
      ort-bypassed: ${{ inputs.ort-bypassed }}
      ort-version: ${{ inputs.ort-version }}
      trivy-enabled: ${{ inputs.trivy-enabled }}
      trivy-bypassed: ${{ inputs.trivy-bypassed }}
      trivy-severity: ${{ inputs.trivy-severity }}
      trivy-severity-for-sarif: ${{ inputs.trivy-severity-for-sarif }}
      trivy-limit-severities-for-sarif: ${{ inputs.trivy-limit-severities-for-sarif }}
      python-version: ${{ inputs.python-version }}

  build:
    runs-on: ubuntu-22.04 # TODO: ubuntu-latest have python 3.12 by default and breaks `pip install` system-wide packages
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
      - uses: epam/ai-dial-ci/actions/python_prepare@2.0.1
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
      - run: make build
