name: Python test build

on:
  workflow_call:
    inputs:
      bypass_checks:
        type: boolean
        default: false
        description: Do not fail pipeline if checks failed
      bypass_ort:
        type: boolean
        default: false
        description: Do not fail pipeline if ORT failed
      python_version:
        type: string
        default: '3.11'
        description: Python version to use

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  style_checks:
    runs-on: ubuntu-latest
    steps:
      - name: PR title check
        uses: thehanimo/pr-title-checker@5652588c80c479af803eabfbdb5a3895a77c1388 #v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: epam/ai-dial-ci/actions/prepare_python@1.0.0
        with:
          python_version: ${{ inputs.python_version }}
          install_poetry: true
      - name: Test
        continue-on-error: ${{ inputs.bypass_checks }}
        shell: bash
        run: |
          make lint

  code_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: epam/ai-dial-ci/actions/prepare_python@1.0.0
        with:
          python_version: ${{ inputs.python_version }}
          install_poetry: true
      - name: Test
        continue-on-error: ${{ inputs.bypass_checks }}
        shell: bash
        run: |
          make test

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
        with:
          lfs: true
      - uses: epam/ai-dial-ci/actions/build_docker@1.0.0
        with:
          image_name: ghcr.io/${{ env.IMAGE_NAME }}
          image_tag: test
          push: false
          scan: true

  ort:
    runs-on: ubuntu-latest
    steps:
      - uses: epam/ai-dial-ci/actions/prepare_python@1.0.0
        with:
          python_version: ${{ inputs.python_version }}
          install_poetry: true
      - name: Install dependencies
        shell: bash
        run: |
          poetry install --all-extras
      - uses: epam/ai-dial-ci/actions/ort@1.0.0
        with:
          bypass_checks: ${{ inputs.bypass_ort }}
