# sample reusable workflow that runs `ls -alh` and prints environment variables

name: Reusable workflow

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List files
        run: ls -alh

  other_test:
    runs-on: ubuntu-latest

    steps:
      - name: env test
        run: env | sort
      - name: gh data test
        env:
          JSON_DOC: ${{ toJSON(github) }}
        run: echo "$JSON_DOC" | jq '.'