name: Trigger integration tests

on:
  workflow_call:

jobs:
  trigger_tests:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.issue.pull_request && contains(github.event.comment.body, 'test') && github.actor == 'justrp' # TODO: either list all actors, or figure out how to check team membership
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_REF_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
          PR_REF_BRANCH: ${{ github.head_ref }}
          JSON_GITHUB: ${{ toJson(github) }}
          #TOKEN: ${{ secrets.PIPELINE_TRIGGER_TOKEN }}
          #PIPELINE_TRIGGER_URL: ${{ secrets.PIPELINE_TRIGGER_URL }}
        run: |
          echo "Not implemented yet"
          # Debug
          echo $JSON_GITHUB
#          curl -X POST \
#             --fail \
#             -F "token=${TOKEN}" \
#             -F "ref=main" \
#             -F "variables[CORE_VERSION]=${PR_NUMBER}-${PR_REF_OWNER}/${PR_REF_BRANCH}" \
#             "${PIPELINE_TRIGGER_URL}" ||
